### PR TITLE
Side menu bar ui fix

### PR DESCRIPTION
**Pull request by dhanesh12twice**
Hello, Im new to flutter . I checked out your repo. Its pretty good. I cloned and played with it. I fixed some yellow box UI errors. So I wished to push the changes with you. =

### CODE REVIEW

**Comment by AminBhst** [comment]
Hey, thank you for your contribution and interest in the project. 
The changes seem to be fine. However there is one thing I would like to add. With theses changes the setting button loses its bottom margin and the setting button gets way too close to the bottom of the screen. Maybe add a bottom padding of about 20 or 30 and I will merge your changes.

Also if you were by any chance interested in contributing more, I have opened a new issue here #25 that is relatively simple.

**Comment by dhanesh12twice** [comment]
@AminBhst  Thanks for the response. Yes I'll add the padding and push the changes.  #25 I'll look into it. Thank you

**Comment by dhanesh12twice** [comment]
Yes @AminBhst Ive added bottom padding for Settings icon as you mentioned. please have a look and tell me if you need anyother changes

**Comment by AminBhst** [comment]
LGTM
thank you for the contribution

**Pull request merged**
